### ISSUE TITLE
Code does not compile 64-bit.

### ISSUE THREAD

**Issue by ReddestDream** [vit9696/CorrectOpenVPN#1]
When attempted to compile 64-bit, I get the error:

Tweak.xm:38:22: error: cast from pointer to smaller type 'unsigned int' loses information

I researched this a bit and found this:

https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaTouch64BitGuide/ConvertingYourAppto64-Bit/ConvertingYourAppto64-Bit.html

So, I changed the "unsigned int" on line 38 to "uintptr_t".

This solved the error and allowed it to compile.

I don't really know how to code though, and I'm just playing around trying to fix this.

If this is the right fix, go ahead and add it in. If not, please let me know. Thanks! ^_^

Edit: I got confirmation here that my fix works:

https://www.reddit.com/r/jailbreak/comments/3bz7gx/release_correctopenvpn_fixes_openvpn_connect/csraxwx

Please find here all of the modifications I made for your perusal:

http://wikisend.com/download/282812/CorrectOpenVPN.zip

Edit: The pull request by CODYQX4 contains all my changes plus a fix for another issue.

**Comment by vit9696** [comment]
This should be fixed now.

**Comment by ReddestDream** [comment]
Thanks! ^_^
